### PR TITLE
Create dowker_nest

### PR DESCRIPTION
**Pull request by toaltman**
dowker_cosheaf <- function(df,left_var,right_var){
  df %>%
    ungroup() %>%
    select({{left_var}},{{right_var}}) %>%
    nest(simplex={{left_var}}) %>%
    group_by(simplex) %>%
    nest(costalk={{right_var}}) %>%
    mutate(weight=sapply(costalk,function(x){nrow(x)}),
           dimension=sapply(simplex,function(x){nrow(x)-1})) %>%
    ungroup()
}

### CODE REVIEW

**Comment by kb1dds** [comment]
@jaehee99 has a newer version of this... she can drop in the appropriate code in a comment!

**Comment by toaltman** [comment]
Great, thank you!

**Comment by jjhee17** [comment]
Here is the newest version of Dr.Robinson's dowker code: 

dowker_nest <- function(df,feature_vars,obs_vars){
  df %>%
    ungroup() %>%
    select({{feature_vars}},{{obs_vars}}) %>%
    nest(feature_pattern={{feature_vars}}) %>%
    group_by(feature_pattern) %>%
    nest(observations={{obs_vars}}) %>%
    mutate(weight=sapply(observations,function(x){nrow(x)}),
           feature_count=sapply(feature_pattern,function(x){nrow(x)})) %>%
    ungroup()
}

**Comment by kb1dds** [comment]
This looks good!  Go ahead and merge please

**Comment by jjhee17** [comment]
This is good!

**Pull request merged**
